name: northstar_analytics
version: 1.0.0
config-version: 2

profile: northstar_analytics
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  northstar_analytics:
    example:
      +schema: example
      +materialized: view
